(when (require 'google-c-style nil t)
  (add-hook 'c-mode-hook 'google-set-c-style)
  (add-hook 'c++-mode-hook 'google-set-c-style)
  (add-hook 'c-mode-hook 'google-make-newline-indent)
  (add-hook 'c++-mode-hook 'google-make-newline-indent))
