(require 'tide)
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-mode))
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))
(add-hook 'typescript-mode-hook
          (lambda()
            (interactive)
            (tide-setup)            
            (tide-hl-identifier-mode +1)
            (company-mode +1)
            (eldoc-mode +1)))
