(setq custom-theme-directory "~/.emacs.d/themes/")
(load-theme 'deeper-blue)
;;(load-theme 'mytheme t)
;;(enable-theme 'mytheme)
;;(add-to-list 'default-frame-alist '(alpha . 85))
(set-frame-parameter nil 'alpha 1.0)
(setq show-paren-style 'parenthesis)
